

.PHONY : TARGET0
TARGET0 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/add-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/add-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/add-01.S/dut;

.PHONY : TARGET1
TARGET1 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/addi-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/addi-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/addi-01.S/dut;

.PHONY : TARGET2
TARGET2 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/addiw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/addiw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/addiw-01.S/dut;

.PHONY : TARGET3
TARGET3 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/addw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/addw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/addw-01.S/dut;

.PHONY : TARGET4
TARGET4 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/and-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/and-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/and-01.S/dut;

.PHONY : TARGET5
TARGET5 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/andi-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/andi-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/andi-01.S/dut;

.PHONY : TARGET6
TARGET6 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/auipc-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/auipc-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/auipc-01.S/dut;

.PHONY : TARGET7
TARGET7 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/beq-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/beq-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/beq-01.S/dut;

.PHONY : TARGET8
TARGET8 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/bge-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/bge-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/bge-01.S/dut;

.PHONY : TARGET9
TARGET9 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/bgeu-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/bgeu-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/bgeu-01.S/dut;

.PHONY : TARGET10
TARGET10 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/blt-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/blt-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/blt-01.S/dut;

.PHONY : TARGET11
TARGET11 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/bltu-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/bltu-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/bltu-01.S/dut;

.PHONY : TARGET12
TARGET12 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/bne-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/bne-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/bne-01.S/dut;

.PHONY : TARGET13
TARGET13 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/fence-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/fence-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/fence-01.S/dut;

.PHONY : TARGET14
TARGET14 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/jal-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/jal-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/jal-01.S/dut;

.PHONY : TARGET15
TARGET15 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/jalr-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/jalr-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/jalr-01.S/dut;

.PHONY : TARGET16
TARGET16 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/lb-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/lb-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/lb-align-01.S/dut;

.PHONY : TARGET17
TARGET17 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/lbu-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/lbu-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/lbu-align-01.S/dut;

.PHONY : TARGET18
TARGET18 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/ld-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/ld-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/ld-align-01.S/dut;

.PHONY : TARGET19
TARGET19 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/lh-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/lh-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/lh-align-01.S/dut;

.PHONY : TARGET20
TARGET20 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/lhu-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/lhu-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/lhu-align-01.S/dut;

.PHONY : TARGET21
TARGET21 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/lui-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/lui-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/lui-01.S/dut;

.PHONY : TARGET22
TARGET22 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/lw-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/lw-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/lw-align-01.S/dut;

.PHONY : TARGET23
TARGET23 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/lwu-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/lwu-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/lwu-align-01.S/dut;

.PHONY : TARGET24
TARGET24 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/misalign1-jalr-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/misalign1-jalr-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/misalign1-jalr-01.S/dut;

.PHONY : TARGET25
TARGET25 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/or-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/or-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/or-01.S/dut;

.PHONY : TARGET26
TARGET26 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/ori-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/ori-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/ori-01.S/dut;

.PHONY : TARGET27
TARGET27 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sb-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sb-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sb-align-01.S/dut;

.PHONY : TARGET28
TARGET28 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sd-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sd-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sd-align-01.S/dut;

.PHONY : TARGET29
TARGET29 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sh-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sh-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sh-align-01.S/dut;

.PHONY : TARGET30
TARGET30 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sll-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sll-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sll-01.S/dut;

.PHONY : TARGET31
TARGET31 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/slli-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/slli-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/slli-01.S/dut;

.PHONY : TARGET32
TARGET32 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/slliw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/slliw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/slliw-01.S/dut;

.PHONY : TARGET33
TARGET33 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sllw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sllw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sllw-01.S/dut;

.PHONY : TARGET34
TARGET34 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/slt-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/slt-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/slt-01.S/dut;

.PHONY : TARGET35
TARGET35 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/slti-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/slti-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/slti-01.S/dut;

.PHONY : TARGET36
TARGET36 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sltiu-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sltiu-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sltiu-01.S/dut;

.PHONY : TARGET37
TARGET37 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sltu-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sltu-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sltu-01.S/dut;

.PHONY : TARGET38
TARGET38 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sra-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sra-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sra-01.S/dut;

.PHONY : TARGET39
TARGET39 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/srai-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/srai-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/srai-01.S/dut;

.PHONY : TARGET40
TARGET40 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sraiw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sraiw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sraiw-01.S/dut;

.PHONY : TARGET41
TARGET41 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sraw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sraw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sraw-01.S/dut;

.PHONY : TARGET42
TARGET42 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/srl-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/srl-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/srl-01.S/dut;

.PHONY : TARGET43
TARGET43 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/srli-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/srli-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/srli-01.S/dut;

.PHONY : TARGET44
TARGET44 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/srliw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/srliw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/srliw-01.S/dut;

.PHONY : TARGET45
TARGET45 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/srlw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/srlw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/srlw-01.S/dut;

.PHONY : TARGET46
TARGET46 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sub-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sub-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sub-01.S/dut;

.PHONY : TARGET47
TARGET47 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/subw-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/subw-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/subw-01.S/dut;

.PHONY : TARGET48
TARGET48 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sw-align-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/sw-align-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/sw-align-01.S/dut;

.PHONY : TARGET49
TARGET49 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/xor-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/xor-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/xor-01.S/dut;

.PHONY : TARGET50
TARGET50 :
	@cd /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/xori-01.S/dut; riscv64-unknown-elf-gcc -march=rv64i          -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -g         -T /home/owais/nucleusrv/nucleusrv/env/link.ld         -I /home/owais/nucleusrv/nucleusrv/env/         -I /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/env /home/owais/nucleusrv/riscv-arch-test/riscv-test-suite/rv64i_m/I/src/xori-01.S -o my.elf  -DTEST_CASE_1=True -DXLEN=64 -mabi=lp64 ; /home/owais/nucleusrv/simcmd.sh /home/owais/nucleusrv/riscof_work/rv64i_m/I/src/xori-01.S/dut;